#!/bin/bash 
#: Title : hw 
#: Date : 2014-04-21 
#: Author : "Ander Raso" <anderraso@gmail.com> 
#: Version : 1.0 
#: Description : print Hello, World! 
#: Options : None

printf "%s\n" "Hello, World!"
